### ISSUE TITLE
CREST Auth does not work as Callback URL validation has changed.

### ISSUE THREAD

**Issue by Tokeiito** [georgwacker/EveMarketProphet#4]
At current moment, it is impossible to create application with callback url '/'. User needs to provide protocol, which can be http, https or eveauth-app:// something.

Cause that, generated link does not work and Refresh token is never generated and or created.

**Comment by Juvecu** [comment]
I'm really interested in using your application, I've done a lot of research and I think it's one of the best implementations of a trading tool. As Tokeiito has pointed out the process for creating a new app in the EVE Online Developer Portal now does not allow the use of "/" as a callback URL any more.

Pyfa, a ship fitting tool, uses a lightweight mini web server and the callback URL is set to point to that. If you're behind a router you'd need to forward a port for this to work, I imagine. Perhaps looking at Pyfa's code here on GitHub will help with updating this application to support the current callback URL format?

Pyfa: https://github.com/pyfa-org/Pyfa

If I had any decent programming skills I would be more than willing to do this myself, but I'm still hopeless when it comes to coding anything complicated.

Can you give us an indication on whether you'll be able to fix this?

**Comment by ghost** [comment]
According to https://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/authentication.html

When a user clicks the login button on your website you need to redirect the user to https://login.eveonline.com/oauth/authorize with the following query string parameters:

    response_type: Must be set to “code”.
    redirect_uri: After authentication the user will be redirected to this URL on your website. It must match the definition on file in the developers site.
    client_id: A string identifier for the client, provided by CCP.
    scope: The requested scopes as a space delimited string.
    state: An opaque value used by the client to maintain state between the request and callback. The SSO includes this value when redirecting back to the 3rd party website. While not required, it is important to use this for security reasons. http://www.thread-safe.com/2014/05/the-correct-use-of-state-parameter-in.html explains why the state parameter is needed.

**Comment by georgwacker** [comment]
I'm working on an update right now to implement the new ESI API and authentication flow.

**Comment by georgwacker** [comment]
Fixed in v1.1
